name: CI (Simulated Deploy)

on:
  pull_request:
  push:
    branches: [ main, develop, feat/** ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # go-version: '1.23'
          go-version-file: 'go.mod'


      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m --out-format=colored-line-number,github-actions

      - name: Run tests
        run: go test ./...

  
  build-docker:
    name: Build Docker Image
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t myapp:${{github.sha}} .
    

  push-image:
    name: Push Docker Image to GHCR
    needs: build-docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image with tag
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest



        
  # deploy:
  #   name: Deploy to Server
  #   needs: build-docker
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /app/myapp
  #           docker pull myapp:${{ github.sha }}
  #           docker compose down
  #           docker compose up -d

  deploy-simulated:
    name: ðŸš€ Simulated Deploy (No real server)
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deploy step
        run: |
          echo "âœ… Build and tests passed!"
          echo "ðŸš€ Simulating deploy process..."
          echo "Pushing Docker image (simulated)..."
          sleep 2
          echo "Deploying to server (simulated)..."
          sleep 2
          echo "Deployment complete (simulation only)."
